dist: bionic
language: perl
os: linux
if: tag IS blank AND env(GITHUB_OAUTH_TOKEN) IS present AND type IN (push, pull_request)
perl:
  - "5.30"
addons:
  apt:
    packages:
    - git
    - wget
    - file
    - build-essential
    - libssl-dev
    - libexpat1-dev
    - cpanminus
    - libz-dev
    - ncbi-blast+
    - g++
    - libdb-dev
cache:
  directories:
  - perl_modules
before_install:
- cpanm local::lib
- eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
- cpanm --notest Dist::Zilla

install:
- "source ./install_dependencies.sh"
- dzil authordeps --missing | cpanm --notest
- dzil listdeps --missing | cpanm --notest
script: 
- dzil test
- dzil build
